import 'package:core/core.dart';

import 'direction_sighting_local_store.dart';

/// The `direction_sighting_submit` task of the offline queue (decision 28
/// applied to DS2): a sighting survives being offline at the moment of
/// tapping, same offline-queue treatment as every other write in this
/// app. The clientKey generated by the repository travels IN the
/// payload, so a replayed dispatch is answered 200/201 by the API and
/// treated as success here (decision 137's idempotency), mirroring
/// `rating_queue_tasks.dart` exactly.
abstract final class DirectionSightingQueueTasks {
  static const submit = 'direction_sighting_submit';

  /// Wires the handler. Call once at bootstrap next to
  /// `ReportQueueTasks`/`ChatQueueTasks`/`RatingQueueTasks`/
  /// `PanicQueueTasks`, before any flush. [localStore] is optional only
  /// for tests that do not care about the local bookkeeping — production
  /// always passes it. The repository already records the "already
  /// sighted" mark at ENQUEUE time (so a revisit before this flush runs
  /// never re-offers the picker); saving it again here on success is a
  /// harmless, defensive no-op for any task that somehow reaches this
  /// handler without having gone through the repository first.
  static void register(OfflineQueueService queue, ApiClient apiClient,
      {DirectionSightingLocalStore? localStore}) {
    queue.register(submit, (payload) async {
      final reportId = payload['reportId'] as int;
      final direction = DirectionJson.fromJson(payload['direction'] as String);
      try {
        await apiClient.post('/app-direction-sightings', {
          'reportId': reportId,
          'direction': direction.wire,
          'clientKey': payload['clientKey'],
        });
      } on Failure catch (failure) {
        return _judge(failure);
      }
      await localStore?.saveSighting(reportId: reportId, direction: direction);
      return QueueTaskResult.done;
    });
  }

  /// 5xx is the API having a bad moment — retry keeps the task. Anything
  /// else was judged (404/422 DIRECTION_SIGHTING_NOT_ELIGIBLE/422
  /// BUSINESS_RULE/451): retrying can never succeed, so the task is
  /// dropped rather than wedging the queue forever — same rule as every
  /// other queue task in this app.
  static QueueTaskResult _judge(Failure failure) =>
      (failure.statusCode ?? 0) >= 500 ? QueueTaskResult.retry : QueueTaskResult.drop;
}
