import 'package:core/core.dart';

import '../../../shared/data/my_reports_store.dart';

/// The `rating_submit` task of the offline queue (decisions 28/181/183):
/// a rating IS meant to survive being offline at the moment of resolving
/// — the clientKey generated by the repository travels IN the payload, so
/// a replayed dispatch is answered 200/201 by the API and treated as
/// success here, exactly like `report_queue_tasks.dart`/`chat_queue_tasks.dart`.
abstract final class RatingQueueTasks {
  static const submit = 'rating_submit';

  /// Wires the handler. Call once at bootstrap next to
  /// `ReportQueueTasks`/`ChatQueueTasks`, before any flush.
  static void register(OfflineQueueService queue, ApiClient apiClient,
      {MyReportsStore? myReports}) {
    queue.register(submit, (payload) async {
      final reportId = payload['reportId'] as int;
      final offerId = payload['offerId'] as int;
      final ownerKey = await myReports?.clientKeyOf(reportId);
      try {
        await apiClient.post(
          '/app-reports/$reportId/offers/$offerId/rating',
          {'score': payload['score'], 'clientKey': payload['clientKey']},
          // Bearer ownership for the anonymous reporter (decision 134) —
          // header, never URL.
          headers: ownerKey == null ? null : {'x-client-key': ownerKey},
        );
      } on Failure catch (failure) {
        return _judge(failure);
      }
      return QueueTaskResult.done;
    });
  }

  /// 5xx is the API having a bad moment — retry keeps the task. Anything
  /// else was judged (404/409 ALREADY_RATED/409 RATING_CLOSED/422/451):
  /// retrying can never succeed, so the task is dropped rather than
  /// wedging the queue forever — same rule as every other queue task in
  /// this app.
  static QueueTaskResult _judge(Failure failure) =>
      (failure.statusCode ?? 0) >= 500 ? QueueTaskResult.retry : QueueTaskResult.drop;
}
